server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.54.33.134:3306/tensquare_friend?characterEncoding=UTF8
    username: root
    password: 123456
    jpa:
      database: MySQL
      show-sql: true
    redis:
      host: 106.54.33.134

jwt:
  config:
    key: zhangwj
    ttl: 0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true

