#server:
#  port: 9008
#spring:
#  application:
#    name: tensquare-user #指定服务名
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://106.54.33.134:3306/tensquare_user?characterEncoding=UTF8
#    username: root
#    password: 123456
#  jpa:
#    database: MySQL
#    show-sql: true
#  redis:
#    host: 106.54.33.134
#  rabbitmq:
#    host: 106.54.33.134
#
#jwt:
#  config:
#    key: zhangwj
#    ttl: 3600000 #令牌过期时间1小时
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:6868/eureka/
#  instance:
#    prefer-ip-address: true
