server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.54.33.134:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 106.54.33.134
  rabbitmq:
    host: 106.54.33.134
